spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbuser
    username: root
    password: 12345
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true



logging:
  level: debug




